Backfill performance
figment-networks/polkadothub-indexer pull request #30
Opened 2020-10-16 19:10 UTC by eesmerdag

2020-10-16 19:12 UTC, eesmerdag commented
https://www.notion.so/figmentnetworks/Find-a-best-way-to-speed-up-the-process-of-backfilling-data-354c1ef5a2c84b708d281159d0d29393

2020-10-20 04:04 UTC, pacmessica reviewed
good job, left some minor comments.

2020-10-20 04:04 UTC, pacmessica commented on store/syncables_store.go
> +func (s SyncablesStore) FindSpecificHeightsByLastInSessionsAndLastInSessionsEras(indexVersion int64, isForLastOfSessions, isForLastOfEras bool) ([]model.Syncable, error) {
I think it makes sense to search for these in a range. We don't really need to return every single last in session syncable, in backfill_source we're only interested in the ones between startHeight and endHeight. 

So I think searching by range is good and breaking it up into two separate calls would be cleaner. something like `FindAllLastInSessionForRange(indexVersion, startHeight, endHeight)`, `FindAllLastInEraForRange(indexVersion, startHeight, endHeight)`


then in backfill_source you could do something like:
```
if isForLastOfSessions {
   syncables, err := s.db.Syncables.FindAllLastInSessionForRange(s.currentIndexVersion, s.startHeight, s.endHeight)
}
```

what do you think?

2020-10-20 12:05 UTC, eesmerdag commented on go.mod
> +	github.com/figment-networks/indexing-engine v0.1.13
hmm yes, i am changing it for now :)

2020-10-20 12:20 UTC, eesmerdag commented on indexer/source_backfill.go
> +	specificHeightsMap                map[int64]int64
but we have two parameters to use while fetching data, i need them when running query so lets keep them as it is for now

2020-10-20 12:21 UTC, eesmerdag commented on indexer/source_backfill.go
> +		}
sure i will change it

2020-10-20 12:21 UTC, eesmerdag commented on indexer/source_index.go
> +	return s.skipRunningStagesForCurrentHeight
hmmmm but the default value is false then i decided to return skipRunningStagesForCurrentHeight. let me try to remove skipRunningStagesForCurrentHeight first.

2020-10-20 12:52 UTC, eesmerdag commented on store/syncables_store.go
> +func (s SyncablesStore) FindSpecificHeightsByLastInSessionsAndLastInSessionsEras(indexVersion int64, isForLastOfSessions, isForLastOfEras bool) ([]model.Syncable, error) {
Then i have to send two different queries to db and change the code a bit. I guess we can skip this.

2020-10-20 12:53 UTC, eesmerdag commented on store/syncables_store.go
> +func (s SyncablesStore) FindSpecificHeightsByLastInSessionsAndLastInSessionsEras(indexVersion int64, isForLastOfSessions, isForLastOfEras bool) ([]model.Syncable, error) {
hmmmm i will change the method name :D

2020-10-20 14:31 UTC, pacmessica commented on indexer/source_backfill.go
> +	specificHeightsMap                map[int64]int64
What I mean is that you only really need `isForLastOfSessions` and `isForLastOfEras` on init, so rather than making them part of this struct you could just pass them into `setSpecificHeights` as a param instead. Then you can simplify the struct.

2020-10-20 14:38 UTC, pacmessica commented on indexer/source_backfill.go
> +		syncables, err := s.db.Syncables.FindSpecificHeights(s.currentIndexVersion, s.isForLastOfSessions, s.isForLastOfEras)
I don't think this name is descriptive. `SpecificHeights` doesn't make sense to anywhere in the code except backfill_source. Imagine we want to reuse this function somewhere else.

This method finds all syncables that are last in session and/or last in era. So a more descriptive name would be  `FindAllByLastInSessionOrEra`

2020-10-20 15:04 UTC, eesmerdag commented on indexer/source_backfill.go
> +		syncables, err := s.db.Syncables.FindSpecificHeights(s.currentIndexVersion, s.isForLastOfSessions, s.isForLastOfEras)
👍

2020-10-20 15:09 UTC, eesmerdag commented on indexer/source_backfill.go
> +	specificHeightsMap                map[int64]int64
Then i will need another parameter to keep if it has specific heights or not as boolean. I guess for now it is fine ?

2020-10-22 10:49 UTC, silentlight reviewed
First round looks promising. Good job. Left few comments

2020-10-22 10:49 UTC, silentlight commented on indexer/source_backfill.go
> +	specificHeightsMap  map[int64]int64
Let's use `heightsWhitelist` here to be consistent with what we use for pipeline options.

2020-10-22 10:49 UTC, silentlight commented on store/syncables_store.go
> +func (s SyncablesStore) FindAllByLastInSessionOrEra(indexVersion int64, isForLastOfSessions, isForLastOfEras bool) ([]model.Syncable, error) {
Can we use isLastInSession and isLastInEra here to be consistent with names in db?

2020-10-22 10:49 UTC, silentlight commented on indexer/source_backfill.go
> +func (s *backfillSource) setSpecificHeights() error {
So I think this method should be up one level. So ideally we will be passing a slice of height to this source.

2020-10-22 10:49 UTC, silentlight commented on indexer/config_parser.go
> +	lastVersion := o.targets.Versions[len(o.targets.Versions)-1]
In this struct we already have `GetCurrentVersionId` which you can use here. And you can also change lastVersion to currentVersion to make it consistent. Also, I think that just having names `IsLastInSession` and `IsLastInEra` will be enough here and consistent with other parts of the codebase. I also think this this method should expect versionId as parameter and we can pass current version id from upper level.

2020-10-22 11:39 UTC, eesmerdag commented on indexer/source_backfill.go
> +	specificHeightsMap  map[int64]int64
👍

2020-10-22 11:48 UTC, eesmerdag commented on store/syncables_store.go
> +func (s SyncablesStore) FindAllByLastInSessionOrEra(indexVersion int64, isForLastOfSessions, isForLastOfEras bool) ([]model.Syncable, error) {
👍

2020-10-22 12:14 UTC, eesmerdag commented on indexer/config_parser.go
> +	lastVersion := o.targets.Versions[len(o.targets.Versions)-1]
👍

2020-10-22 12:40 UTC, eesmerdag commented on indexer/source_backfill.go
> +func (s *backfillSource) setSpecificHeights() error {
then we need to move the other methods setStartHeight and setEndHeight where all these methods are called in Init function. or we change the name for all the methods instead of  set -> fetch etc? https://github.com/figment-networks/polkadothub-indexer/blob/054ccd59b858b45ffbd2d8a35d97829ca87b3a3f/indexer/source_backfill.go#L67

2020-10-22 15:13 UTC, pacmessica commented on indexer/source_index.go
> +	return s.skipRunningStagesForCurrentHeight
this is still open 😛

2020-10-22 17:08 UTC, eesmerdag commented on indexer/source_backfill.go
> +	specificHeightsMap                map[int64]int64
I am not really sure about this. I need those parameters for generating query here: https://github.com/figment-networks/polkadothub-indexer/blob/7cedaea467f12d150af558a7114f9790b9b9e4ba/store/syncables_store.go#L138
So we need two different parameters here. 

by the way, i have changed the names.

2020-10-22 17:16 UTC, pacmessica commented on indexer/source_backfill.go
> +	specificHeightsMap                map[int64]int64
yeah, I know. I said you can pass them as params instead of saving them to the struct. ie like this 

```
func (s *backfillSource) setHeightsWhitelist(isLastInSession, isLastInEra bool) error {
	if s.HasHeightWhiteListToRunStages() {
		syncables, err := s.db.Syncables.FindAllByLastInSessionOrEra(s.currentIndexVersion, isLastInSession, isLastInEra)
		if err != nil {
			if err == store.ErrNotFound {
				return errors.New(fmt.Sprintf("no heights for whitelist to backfill [currentIndexVersion=%d]", s.currentIndexVersion))
			}
			return err
		}
		s.generateMapForWhiteList(syncables)
	}
	return nil
}
```

2020-10-22 17:21 UTC, pacmessica commented on indexer/source_backfill.go
> +	specificHeightsMap                map[int64]int64
then you won't need to save those two vars in the struct, instead you could save `useWhiteList` in the struct, and also delete the method `HasHeightWhiteListToRunStages()`. I think it's cleaner

2020-10-22 17:28 UTC, eesmerdag commented on indexer/source_backfill.go
> +	specificHeightsMap                map[int64]int64
👍

2020-10-23 22:19 UTC, pacmessica commented on indexer/sink.go
> +		if err := s.db.Syncables.UpdateSkippedHeightForBackfill(s.versionNumber, payload.CurrentHeight); err != nil {
I'd prefer fetching the missing syncable and calling setProcessed on it rather than creating a new db method. This is because the logic for updating a syncable  is in `Syncable.MarkProcessed(s.versionNumber)`, and it's nice to keep that logic in one place.

2020-10-23 22:19 UTC, pacmessica commented on indexer/sink.go
> +func (s *sink) Consume(ctx context.Context, p pipeline.Payload, isForOnlyVersion bool) error {
So the problem we're solving here is that when we skip running tasks, we never set payload.Syncable but we still want to mark syncable as processed.

What about heights that we don't skip? Do we not keep metrics data? Do we not update syncable.Duration? With the way it's implemented now, we're treating skipped and non-skipped the same way. This `isForOnlyVersion` flag doesn't tell us which heights are supposed to be skipped. For this reason, I think it'd be better to pass the `heightsWhitelist` to sink so you know what's supposed to be skipped and what's not. Does that make sense?

2020-10-26 11:58 UTC, eesmerdag commented on indexer/sink.go
> +		if err := s.db.Syncables.UpdateSkippedHeightForBackfill(s.versionNumber, payload.CurrentHeight); err != nil {
What i see from the code these are the workers: indexer_start, indexer_backfill, indexer_summarize, indexer_purge etc. Is there an opportunity to skip some heights for update for the other workers too? If not, i would say we can keep the name. Or what is your name suggestion for this method? "updateSkippedHeights"?

2020-10-26 12:37 UTC, eesmerdag commented on indexer/sink.go
> +func (s *sink) Consume(ctx context.Context, p pipeline.Payload, isForOnlyVersion bool) error {
Hmmm I don't think the current code treats skipped and non-skipped the same way. `isForOnlyVersion`  is used in here to represent if the current height to be skipped or not : https://github.com/figment-networks/indexing-engine/blob/5ea558ea82dc61eb1b156fe5e65cf411cfd74a6b/pipeline/pipeline.go#L222 
But i think i can the paramter name, any suggestion for it?

2020-10-26 12:47 UTC, eesmerdag commented on store/syncables_store.go
> +func (s SyncablesStore) UpdateSkippedHeightForBackfill(indexVersion int64, height int64) error {
What i can see from the code these are the worker types: indexer_start indexer_backfill indexer_summarize indexer_purge. Is it possible for the rest too to skip current height?

2020-10-26 12:52 UTC, eesmerdag commented on indexer/sink.go
> +		if err := s.db.Syncables.UpdateSkippedHeightForBackfill(s.versionNumber, payload.CurrentHeight); err != nil {
yes you are right, let me try for it. it is more safer than updating some columns but requies extra query to database. But i concur. i am changing it.

2020-10-26 12:58 UTC, eesmerdag commented on store/syncables_store.go
> +		Exec("UPDATE syncables SET started_at = NOW(), processed_at = NOW(), updated_at = NOW(), duration = 0, index_version = ? WHERE height = ? ", indexVersion, height).
i will change the method by fetching first and then updating

2020-10-26 14:03 UTC, silentlight approved these changes
Left 2 comments @eesmerdag. Let me know if they make sense?

2020-10-26 14:03 UTC, silentlight commented on indexer/source_backfill.go
> +	if s.UseWhiteList() {
You can move UseWhiteList call to line 83

2020-10-26 14:04 UTC, silentlight requested changes
Clicked approve by mistake :p

2020-10-26 18:55 UTC, eesmerdag commented on indexer/source_backfill.go
> +	if s.UseWhiteList() {
👍

2020-10-27 18:05 UTC, pacmessica approved these changes
lgtm

2020-11-09 23:46 UTC, merged